### ISSUE TITLE
updown - WindowsCovering

### ISSUE THREAD

**Issue by chester4444** [Foxi352/homebridge-smarthomeng#2]
Hi, first of all: plugin is working well,

But theres a little problem: 

                {
                    "name": "Rollo Schlafzimmer",
                    "type": "WindowCovering",
                    "updown": "Schlafzimmer.Rollo.Fahren",
                    "currentposition": "Schlafzimmer.Rollo.Position",
                    "targetposition": "Schlafzimmer.Rollo.Position",
                    "inverted": "true"
                }

is it possible to access the "updown" item in smarthome.py

my blind is either sliding to 0 or 100 percent, when tapping on the homekit blind-button
stopping is not possible.

**Comment by Foxi352** [comment]
When you tap and hold your homekit blind-button you should see a slider where you can slide with your finger between 0 and max ?

It works for me, I have standard shutters on a KNX actor. Here is my config as example:

in SmartHomeNG: (in .yaml format)
```
EG:
    Buero:
        Rolladen:

            AufAb:
                type: num
                visu_acl: rw
                knx_dpt: 1
                knx_send: 2/1/3

            Stop:
                type: num
                visu_acl: rw
                enforce_updates: 'yes'
                knx_dpt: 1
                knx_send: 2/5/3

            Position:
                type: num
                visu_acl: rw
                knx_dpt: 5
                knx_listen: 2/4/3
                knx_send: 2/3/3
                knx_init: 2/4/3
```

in homekit:

                {
                    "name": "Rolladen Büro",
                    "type": "WindowCovering",
                    "updown": "EG.Buero.Rolladen.AufAb",
                    "currentposition": "EG.Buero.Rolladen.Position",
                    "targetposition": "EG.Buero.Rolladen.Position",
                    "inverted": true
                }
